### ISSUE TITLE
Double opt in

### ISSUE THREAD

**Issue by janCstoffregen** [nie-ine/inseri#142]
Email zur bestätigung

**Comment by janCstoffregen** [comment]
@ilinde bitte um bestätigung:

Wenn man sich registriert, dann kann man auswählen, dass man den Newsletter erhalten möchte. Dies ist als default in einer Weise gesetzt, dass man keinen Newsletter bekommt (richtig?)

Wenn man dann ankreuzt, bekommt man noch eine Nachricht, dass man ausgewählt hat, dass man einen Newsletter bekommt. In dieser Email ist auch ein Link zur abmeldung, wenn man möchte.

Abschliessend kann man sich in den Usereinstellungen in NIE-OS auch vom Newsletter abmelden.

**Comment by ilinde** [comment]
Ja, das ist gut! Im Newsletter selber sollten wir dann auch jedes Mal einen Link zur Abmeldung haben.

**Comment by janCstoffregen** [comment]
ok

**Comment by janCstoffregen** [comment]
done

**Comment by janCstoffregen** [comment]
fehlt noch für das registrieren --> Email muss noch gesendet werden

**Comment by janCstoffregen** [comment]
not relevant anymore, since new users are added via the system admin
