### ISSUE TITLE
Grundkomponente ATH

### ISSUE THREAD

**Issue by janCstoffregen** [nie-ine/inseri#226]
https://nie-ine.myjetbrains.com/youtrack/issue/ATH-51

App anlegen, parameter auslesen, auch bei parameteränderungen, 

in App - 'Settings' wird die Knora - Instanz festgelegt

**Comment by janCstoffregen** [comment]
depends on #210 -- define string entered by user as input --> define knora instanz

**Comment by janCstoffregen** [comment]
@rfbaumgartner gibt es hierzu eine Youtrack - story? Dann ändere ich den Titel, dann weiss ich, zu wem das gehört.

**Comment by rfbaumgartner** [comment]
Eine solche Grundkomponente ist sehr spezifisch für eine Anwendung. Die Strategie ist aber, möglichst wiederverwendbaren Code zu schreiben.
