### ISSUE TITLE
Pro Query wird geprüft, ob es noch funktioniert

### ISSUE THREAD

**Issue by janCstoffregen** [nie-ine/inseri#237]
@ilinde muss besprochen werden

**Comment by ilinde** [comment]
musst du mir erklären, worum es geht ...

**Comment by janCstoffregen** [comment]
Ich möchte implementieren, dass pro user jede Nacht überprüft wird, ob die Queries noch funktionieren oder ob der Server vll nicht funktioniert. Hat das irgendwelche Auswirkungen auf die Nutzungsbestimmungen / Datenschutzerklärung?

**Comment by ilinde** [comment]
Auf die Nutzungsbestimmungen evtl schon, auf die Datenschutzerklärung nur, wenn dafür die personenbezogenen Daten (die Login-Daten) verarbeitet oder an Dritte weitergegeben werden. Lass uns darüber mal sprechen, ich müsste ein bisschen mehr verstehen, was du da vor hast.

**Comment by janCstoffregen** [comment]
einfach automatisch die Queries auf der Serverseite ausführen und schauen, ob es einen error gibt. ich glaube nicht, dass es Auswirkungen auf die beiden Dokumente hat.

**Comment by janCstoffregen** [comment]
gibt es schon bei anderen software angebiten, zum testen der apis
