### ISSUE TITLE
 Sprachenmix in den Seiten 

### ISSUE THREAD

**Issue by contra8** [nie-ine/inseri#246]
Auf vielen Seiten werden gleichzeitig Texte in deutscher und englischer Sprache angezeigt. Siehe angehängte Screenshots.

Benutzende erwarten wahrscheinlich ein einheitliches Sprachbild.

![2019-04-25_Screenshot Vielsprachigkeit](https://user-images.githubusercontent.com/19752490/56732263-09782900-675d-11e9-883f-0481ade7e7cb.jpg)
![2019-04-25_Screenshot Login](https://user-images.githubusercontent.com/19752490/56732262-09782900-675d-11e9-9cd3-bb4505375660.jpg)

**Comment by rfbaumgartner** [comment]
Es bietet sich an, die Sprache in den Templates gerade in einem Schritt mit der Internationalisierung ( https://angular.io/guide/i18n ) zu erledigen. Für diese müssen nämlich auch die Templates durchgesehen und die einzelnen Texte kommentiert und mit IDs versehen werden. Statt zweimal den Text zu verstehen, kann man das in einem Mal machen.

Ausserdem: Name und Adresse des Services sollten als Variablen eingebunden werden und nicht hartcodiert sein.

**Comment by janCstoffregen** [comment]
we'll do all in english for now
