### ISSUE TITLE
 Overlays sollten umliegende Elemente abdunkeln 

### ISSUE THREAD

**Issue by contra8** [nie-ine/inseri#248]
1. Einloggen
2. Scrollen, bis gelber Button "NACHRICHT ABSCHICKEN" am unteren Browserrand erscheint.
3. Klick in Navigationsleiste oben auf "Einstellungen"
4. Overlay mit Menüpunkten "Profil", "Passwort", "Konto löschen" erscheint.
5. 

"Darunter" liegende Elemente bleiben sichtbar und aktiv (im angehängten Screenshot z. B. der Button "NACHRICHT ABSCHICKEN")
![2019-04-25_Screenshot Abdunkeln erwuenscht](https://user-images.githubusercontent.com/19752490/56732661-5dcfd880-675e-11e9-8fea-c01e4792678e.jpg)
.

**Comment by janCstoffregen** [comment]
Die einfachste Art wäre, das Popup einfach der Fenstergrösse anzupassen :)

**Comment by contra8** [comment]
Bin mir nicht sicher, ob das der Gebrauchstauglichkeit zuträglich wäre. Quasi-Standard ist doch, den Bereich um das Overlay herum mit einer dunklen transparenten Fläche abzudecken.

Diese dunkle Fläche kann dann ebenfalls aktiv gemacht werden, so dass Benutzende viel mehr Fläche haben, um die Box zu schliessen (müssen keine kleinen x oder Buttons suchen).

**Beispiele:**
1. - Klicken auf ein Bild in dieser Galerie: http://www.snf.ch/de/foerderung/wissenschaftskommunikation/bilder-wettbewerb/Seiten/default.aspx#Gewinner%202017
2. - Fancybox Anwendungsbeispiele: http://fancyapps.com/fancybox/3/ - runterscrollen bis Überschrift "Various", dann klicken auf "Hidden HTML element - OPEN DEMO"

**Comment by janCstoffregen** [comment]
ja, es ist sicher besser so!
