### ISSUE TITLE
 Direkter Zugriff aufs Menü "Neue Aktion" ohne Registrierung oder Login möglich 

### ISSUE THREAD

**Issue by contra8** [nie-ine/inseri#249]
1. Browser im Inkognito-Modus starten
2. Seite https://nieos.nie-ine.ch/dashboard aufrufen
3. "Neue Aktion" anklicken

All diese Aufrufe und Aktionen werden ausgeführt, auch wenn man nicht eingeloggt ist.

![2019-04-25_Screenshot Dashboard Direktaufruf ohne Login](https://user-images.githubusercontent.com/19752490/56732792-b1dabd00-675e-11e9-964d-ece463d0d87e.jpg)

**Comment by janCstoffregen** [comment]
Man sollte aber dann keine neue Aktion anlegen können, ist natürlich nicht optimal, das Stichwort ist "protected routes", das muss ich bei manchen Pages noch implementieren, danke für diesen Hinweis!
