### ISSUE TITLE
Mehrere Overlays öffnen sich gleichzeitig

### ISSUE THREAD

**Issue by contra8** [nie-ine/inseri#251]
1. Einloggen
2. Klicken oben rechts auf "Einstellungen"
3. n-mal wiederholen
4. Es öffnen sich n Overlays "EINSTELLUNGEN"
5. n Overlays schliessen durch n-maliges Klicken auf "Schliessen"

Beispielvideo:
https://www.dropbox.com/s/2t7ehemsel7ulxn/2019-04-25%2014.06.55.mp4?dl=0

**Comment by janCstoffregen** [comment]
ist iregndwann mal resolved worden
