### ISSUE TITLE
Which JSON belongs to which page

### ISSUE THREAD

**Issue by Padlina** [nie-ine/inseri#271]
Pages : 
- **Accueil** : just static text (with links to other pages)
- **Le projet** : just static text (with links to other pages)
- **Collaborateurs** : just static text
- **Chant 3** : some static text + JSON :1_chant3.srj
- **Personnes** :  some static text + JSON : 2_gens-de-lettre.srj, 3_savants.srj, 4_artists.srj (as clickable lists of names, with some heading and static text inbetween)
- **Oeuvres** : some static text + JSON: 5_traduction.srj, 6_dictionnaires.srj, 7_anthologies.srj, 8_poesie.srj, 9_roman.srj, 10_memoires.srj, 11_essais.srj, 12_science.srj, 13_catalogues.srj, 14_periodiques.srj (as clickable lists of names, with some heading and static text inbetween)
- **Visualisations des données**

**Comment by janCstoffregen** [comment]
I still don't know which json belongs to which app, so which json belongs to the bar chart etc... would you mind adding this here on in additional issues? Thanks!

**Comment by janCstoffregen** [comment]
@Padlina I still don't know which json belongs to which visualisation.... so, for instance, Chant 3 --> 1_chant3 --> is it a bar chart or to which app does it belong? Do you mind adding this information? Thanks and best regards,
Jan

**Comment by janCstoffregen** [comment]
I see that it is in the explanations, never mind, I saw it now

**Comment by janCstoffregen** [comment]
this is deprecated now, I think
