### ISSUE TITLE
Variables in queries

### ISSUE THREAD

**Issue by janCstoffregen** [nie-ine/inseri#284]
Define a variable in the query that updates by a param in the url

@rfbaumgartner zur info

**Comment by janCstoffregen** [comment]
@rfbaumgartner you're the expert in computer linguistics. Would you mind creating one little typescript function?

**Input**: a string which contains one or more variables, I don't really know how to tag it, maybe §§variableName like this? Also, the second input should be the the value which replaces the variable

**Ouput**: the string where the variable has been replaced by the value.

Please let me know if you have time, I really need it soon and it would be very helpful!
Thank you very much and see you on Tuesday,
Jan

**Comment by rfbaumgartner** [comment]
`InterpolateVariablesInQueriesService` has now been added. The test cases give more information about its usage.

**Comment by domsteinbach** [comment]
Here we could also make use of translating json to sparql and vice versa like this https://github.com/joachimvh/SPARQLAlgebra.js and/or using https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals like this https://github.com/tpluscode/rdf-string

**Comment by janCstoffregen** [comment]
done
