### ISSUE TITLE
Export and import the whole project/pageSet/action

### ISSUE THREAD

**Issue by janCstoffregen** [nie-ine/inseri#294]

**Comment by janCstoffregen** [comment]
download pageSet included everything

**Comment by OmniaKahla** [comment]
For the files and folders, I think it is better to export them while exporting the users.
Please confirm.

**Comment by OmniaKahla** [comment]
Finally, finished.

**Comment by OmniaKahla** [comment]
Added the subPages to the export function

**Comment by OmniaKahla** [comment]
Done
