### ISSUE TITLE
Document src/app/query-engine/knora

### ISSUE THREAD

**Issue by janCstoffregen** [nie-ine/inseri#298]
please document it the following way: 

- [x] one short readme in the root of the Knora folder
- [ ] a short note at the beginning of each file what the file does (not the tests)
- [x] part of the code if necessary

**Comment by rfbaumgartner** [comment]
Most of the code is documented, some services could be safely removed.
The following services should be documented and refactored:

- KnoraAuthService (this is empty but could be included in all Knora services)
- KnoraRequestService (should this be written to a parent of other KnoraV*Services?)
