### ISSUE TITLE
Unable to remove apps from /home

### ISSUE THREAD

**Issue by rfbaumgartner** [nie-ine/inseri#318]
On the start page (/home without login), it is not possible to remove apps through the menu on the left.

To reproduce:

- open the page (should lead to /home)
- Open the Lighthouse menu
- add some apps
- select "remove this app" in the dropdown on the left for this app
- Nothing happens except the message in the console: `TypeError: Cannot convert undefined or null to object at PageComponent.push../src/app/app-engine/page/page/page.component.ts.PageComponent.closeApp` 

Expected outcome:

- the app disappears and is removed from the correct array

**Comment by janCstoffregen** [comment]
done
