### ISSUE TITLE
Apps can communicate without the URL

### ISSUE THREAD

**Issue by janCstoffregen** [nie-ine/inseri#322]
Currently, apps can only communicate by updating the URL. This is not always feasible and an additional option for the apps to communicate will be implemented.

Example: 
Hovering over a word triggers behaviour in another app

**Comment by rfbaumgartner** [comment]
The implementation is started with a variable for hovering in commit https://github.com/nie-ine/NIE-OS/commit/055492c1023ee51ecff81a8627648b9a3055c705

**Comment by rfbaumgartner** [comment]
@janCstoffregen Any more possible cases besides hovering and maybe a main focus? Angular change detection works best if the changed information is in a primitive data type and the implementation the easiest with Input/Output.

**Comment by janCstoffregen** [comment]
... closing for now
