### ISSUE TITLE
User groups

### ISSUE THREAD

**Issue by janCstoffregen** [nie-ine/inseri#326]
This feature includes the ability to create groups in inseri. This eases using inseri as a work environment where different users have different tasks.
Optionally, third party users can register in inseri and comment on published pages if this is enabled by the website – user.
This feature also includes sharing ones page with certain users without the need to publish it.

Examples:
A user defines a group with member that can change, comment or view the website

+ #170

**Comment by lrosenth** [comment]
Could the permission/user system of Knora be of any help?

**Comment by janCstoffregen** [comment]
If Knora offers an API where you send your encrypted credentials to and then get a jwt back that tells inseri which groups and respective roles the user belongs to, that would be great! Then we could use the SUID - GUI to create users and groups!
If a user shares a page with a group, all members of the group can see or edit it, so regarding the permissions it would be simple for me to implement the rest then.

**Comment by janCstoffregen** [comment]
in #405 and april pull request
