### ISSUE TITLE
Position and size of apps doesn't remain

### ISSUE THREAD

**Issue by Padlina** [nie-ine/inseri#361]
Position and size of apps doesn't remain after changing page or going back to dashboard.
Also minimized apps returns visibile on the desktop.

This happen to me with the plaintext viewer app (which kept the widht, but not the height) and Text editor app.

**Comment by Padlina** [comment]
Note: the height of the app remains the same only if you select Full height option in the app settings.

**Comment by janCstoffregen** [comment]
you need to change the size by clicking on the name on the app, then change title and size, then change the width and height, then you need to click on "save page". did you do it this way? I know it's not convenient and will change it, so that you don't need to click "save page" anymore. should I change anything else?

**Comment by Padlina** [comment]
I tried as you said, but it worked for one app (bar chart app), but not for another app (plaintext viewer), even if I always Save the page.

**Comment by Padlina** [comment]
Sorry, my mistake. It does save the position and the size. What make me think that this wasn't the case is this: when you adapt the size with the mouse directly on the app, and then open the menu "Change title and size", the showed number for width and heights doesn't correspond to the actual ones (but correspond to the old ones).

**Comment by Padlina** [comment]
I'll close the issue, my fault.

**Comment by janCstoffregen** [comment]
ok, let me know if and how I can improve it

**Comment by Padlina** [comment]
The only this would be to update the width and height numbers to the actual ones, when modified with the mouse in the desktop, and not only when set in the Settings of the app.
