### ISSUE TITLE
Text Editor App

### ISSUE THREAD

**Issue by Padlina** [nie-ine/inseri#366]
/Open file
- popup "Assign files to app - inputs" needed? => box textFile needed? does something?

=> provide two modes: easy and advanced modes for associating files

**Comment by janCstoffregen** [comment]
- change title from "primeEditor1" to "Text Editor 1"
done

**Comment by janCstoffregen** [comment]
- change title from "primeEditor1" to "Text Editor 1"
- inserting HTML: after one stroke, the curson goes back in the plain text field
- improve "expandability" (usability of everything)

all done

**Comment by janCstoffregen** [comment]
done, I'll publish a new version soon, then you can test it

**Comment by janCstoffregen** [comment]
a new version will be published until the end of the month or earlier
