### ISSUE TITLE
later - Pages

### ISSUE THREAD

**Issue by Padlina** [nie-ine/inseri#370]
- when saving the page, the "alert" message goes to quickly, impossible to read - done
- Extend your session message: also when working? not only when not working? - done
- add Save icon on the top-right (before Settings - Preview) - not at the moment, I'll implemen that page will be saved automatically at some point
- Lighthouse + header + left column (where minimzed apps goes) should always be visible, also when scrolling down the page - done

**Comment by Padlina** [comment]
Two possibilities to test:
- always show app icon in a fold/unfold menu
or
- add option "send to back" "bring to front"

**Comment by Padlina** [comment]
Add automatically save.

**Comment by Padlina** [comment]
the whole header should always be visibile

**Comment by janCstoffregen** [comment]
- if an app isn't minimized, but behind another app, it is not possible to get/move it, without moving first the app on the front. Suggestions: all open apps should be visibile on the left menu (under the Lighthouse).

--> later

**Comment by janCstoffregen** [comment]
- add the possibility to change the background-color of the app (e.g. from grey to white)
--> included in css for pages

**Comment by janCstoffregen** [comment]
top things done, rest later
