### ISSUE TITLE
Enable html response to be mapped to html viewer app

### ISSUE THREAD

**Issue by domsteinbach** [nie-ine/inseri#376]
A hmtl response (html is the content type of the response) can not be mapped to the html viewer app and therefore the html won't be displayed.

**Reproduction:**
Please reproduce the error with the following parameters:
- Data management
- Query Editor (general query editor)
- GET
- Server URL: https://teipublisher.com/exist/apps/tei-publisher/modules/lib/transform.xql?doc=test/F-rom.xml&odd=shakespeare.odd
- URL params and headers not needed

**Result:**
If you try the GET in data management, there is a status: 200 OK, but a HttpErrorResponse with the message: Http failure during parsing. The response though is containing the html: "text : <!DOCTYPE html>  

**Proposed solution:**
Removing the parsing error exception should solve the whole issue.

**Comment by janCstoffregen** [comment]
Hi, tx, I'll try to do it until the 10.2, which would make sense if I understood correctly...

**Comment by domsteinbach** [comment]
Yes, that is the plan.
If you like to reproduce/test it with a smaller file use this as server URL in the query management: http://130.60.24.65:8081/exist/apps/tei-publisher/modules/lib/transform.xql?doc=test/graves6.xml&odd=graves.odd

**Comment by janCstoffregen** [comment]
ok, thank you!

**Comment by janCstoffregen** [comment]
hi, I have introduced the iframe-app now, just open it, then go to file options, change current file, and then enter the address, communication from inseri to the tei publisher would work as well, the other way around I don't know, we'll have to see, can I show it next week?

**Comment by janCstoffregen** [comment]
I'll close it for now
