### ISSUE TITLE
gnd app

### ISSUE THREAD

**Issue by janCstoffregen** [nie-ine/inseri#388]
get gnd info for a person

**Comment by musicEnfanthen** [comment]
see https://www.npmjs.com/package/lobid-client

**Comment by janCstoffregen** [comment]
@musicEnfanthen , can you exchange the localStorage.setItem() in your application by the following please:

```
window.parent.window.postMessage({'for':'user','gnd':'123234X'}, 'http://localhost:4200');
```

... of course replace the 123234X with the regarding variable... 

Thank you!

**Comment by janCstoffregen** [comment]
... http://localhost:4200 bitte so lassen, das zeigt an, unter welcher Adresse inseri läuft, und ich möchte es ja erst einmal lokal weiterentwickeln...

**Comment by musicEnfanthen** [comment]
Ok, can try. Are you sure about the duplicated `window` call. Isn't `window.parent.postMessage` sufficient?

**Comment by janCstoffregen** [comment]
please try it like this, it worked when I tried it

**Comment by musicEnfanthen** [comment]
Done via webern-unibas-ch/awg-app@80648c5204a7bc0a46455491bff5de23497978f1
and running now live with [Version 0.7.1](https://github.com/webern-unibas-ch/awg-app/releases/tag/v0.7.1)

**Comment by janCstoffregen** [comment]
Hi, it works, can you give me another Person with another GND? I already implemented the app and have to test it a little

**Comment by janCstoffregen** [comment]
<img width="1096" alt="Screenshot 2020-02-14 at 14 41 25" src="https://user-images.githubusercontent.com/25609132/74536329-283bec00-4f38-11ea-9285-86193c99835f.png">

**Comment by janCstoffregen** [comment]
and can you **add** a second line to the already existing one, right below:

```
window.parent.window.postMessage({'for':'user','gnd':'123234X'}, 'http://test-nieos.nie-ine.ch/');
```

**Comment by janCstoffregen** [comment]
and please user instead of 

```
{'for':'user','gnd':'123234X'}
```
the following
```
{'param':'gnd','value':'<vairableThatContainsTheValue>'}
```

**Comment by janCstoffregen** [comment]
ok, hab jetzt 2 personen mit einer gnd gefunden, Jokl und Apostel

**Comment by janCstoffregen** [comment]
I'll close this now, it'll work next week as discussed
