### ISSUE TITLE
My first bug: the text we want red is still black

### ISSUE THREAD

**Issue by DDDOlga** [nie-ine/inseri#392]
The html style for changing the text color does not work at least in the "Plain text viewer".
Please see the attached images.

<img width="1388" alt="Screenshot 2020-02-11 at 11 02 17" src="https://user-images.githubusercontent.com/28563965/74227081-09cabc00-4cbe-11ea-9ccf-311b048a2f8c.png">
<img width="802" alt="Screenshot 2020-02-11 at 11 02 31" src="https://user-images.githubusercontent.com/28563965/74227088-0c2d1600-4cbe-11ea-8c06-49400b6ca383.png">
<img width="1403" alt="Screenshot 2020-02-11 at 11 02 06" src="https://user-images.githubusercontent.com/28563965/74227089-0cc5ac80-4cbe-11ea-9082-0c7970a0f9a5.png">

**Comment by DDDOlga** [comment]
The color is not displayed in the "Plain text viewer" as per 2020.03.25, even with files from the editor being relinked, or the source code copy-pasted.
<img width="1359" alt="Screenshot 2020-03-25 at 11 39 04" src="https://user-images.githubusercontent.com/28563965/77528020-7d4f1400-6e8d-11ea-85fc-50ebf0607672.png">

**Comment by DDDOlga** [comment]
The alignment is also ignored by the Viewer. Could it be that JSON needs some more/less "escape" signs to read the HTML?

**Comment by janCstoffregen** [comment]
thanks, I'll have a look!!!

**Comment by janCstoffregen** [comment]
done
