### ISSUE TITLE
Not able to map json response from SPARQL query

### ISSUE THREAD

**Issue by cyrill-martin** [nie-ine/inseri#403]
1. I'm logged in with Hugues Marchal's inseri credentials, working on the Delille edition (DokuWiki Collage).
2. I'm on the start page (Accueil).
3. I created a query to http://fuseki.nie-ine.ch/delille/query in order to retrieve HTML for the start page. Title of the query: **Delille static pages**
4. The query works, I get back a JSON response. 
5. I want to map an element of the JSON to the Plaintext Viewer App. 
6. I open Data Management.
7. I click on ( textlist ) and then on ( map ) in order to map "Delille static pages" with "textlistViewers 0".
8. It doesn't show any query results to map.
`message: "Http failure response for http://test-node.nie-ine.ch/api/pages/5e5f5804fd54d5001ea466e5/queries/5e5f9d23fd54d5001ea46703: 404 Not Found"`

**Comment by janCstoffregen** [comment]
should work again now, please test

**Comment by cyrill-martin** [comment]
works!
