### ISSUE TITLE
Make visualization app display json response dynamicly

### ISSUE THREAD

**Issue by domsteinbach** [nie-ine/inseri#404]
Please make our visualization apps consume json responses from endpoints so the following user story and requirements are forfilled in inseri:

**User story:**

- a superuser defines an http post in data management to a SPARQL endpoint
- maps it to a d3 visualization app
- the data coming from the endpoint will be displayed as a d3 visualization as desired

**Further requirements** 
- data coming from other apps like a generic search app should also be translated to a d3 consumable structure and be displayed in our visualization apps
- Updates of the datastream should also update the visualizations, i.e. a new JSON response requested by an app should also trigger changes in the visualizations app.

**Comment by domsteinbach** [comment]
**Implementation proposals:**

My proposals to deal with it:

1. add npm module https://github.com/zazuko/d3-sparql
2. integrate it into our visualization app by defining an endpoint and a query (Your can use the neat examples in the readme of https://github.com/zazuko/d3-sparql ) and add a simple method using
```
d3.sparql(endpoint, query)
  .then((data) => …);
```
3. Testrun it and make sure our visualization apps can consume the resulting d3 conform JSON

4. Separate the functionality from the visualization app:
- use the http-post/get functionality from the data management app in first place. (Preferably develop services for querying/sending/retrieving in general: Querying for data/an http request should be done by a service and reusable by any other app like a generic search.)
- Separate also the JSON transformation from the visualization app itself. The visualization app should only get a JSON as input which is already in the d3 conform data structure. Make sure changes in the data source trigger changes in the visualization.

**Comment by janCstoffregen** [comment]
can we try to do this with the microservices?

**Comment by janCstoffregen** [comment]
I change this to the high priority milestone for now, ok?
