### ISSUE TITLE
subpage frontend

### ISSUE THREAD

**Issue by janCstoffregen** [nie-ine/inseri#410]
done in the backend

- [x] #400 subPage model and routes ✓

@Padlina @cyrill-martin

**Comment by janCstoffregen** [comment]
@Padlina and @cyrill-martin please have a look at the subpage frontend and let @OmniaKahla know if it's ok now

**Comment by OmniaKahla** [comment]
@janCstoffregen Sorry I still have one commit to be pushed first and then it could be tested.
@cyrill-martin @Padlina 
I’ll confirm once again when it is finished 
Thanks

**Comment by janCstoffregen** [comment]
@OmniaKahla I needed to update an instance, so I redid the changes for now, we can have a look at it later

**Comment by OmniaKahla** [comment]
Done
