### ISSUE TITLE
Text editor 2 save buttons are confusing

### ISSUE THREAD

**Issue by DDDOlga** [nie-ine/inseri#416]
There are two options to "save" in the Text editor, one as the last in the top right hand corner, the other is down. The user might be confused, lets remove "Save" from the upper line, more over it precisely does not "save" the entered info.
<img width="717" alt="8" src="https://user-images.githubusercontent.com/28563965/77516849-61427700-6e7b-11ea-9193-4d0897363c79.png">

**Comment by DDDOlga** [comment]
Well, the upper one does save also, if the internet connection is good enough...

**Comment by janCstoffregen** [comment]
should I just write "export" then?
@domsteinbach how do you export stuff in the data management view?

**Comment by janCstoffregen** [comment]
done
