### ISSUE TITLE
define apps to delete

### ISSUE THREAD

**Issue by janCstoffregen** [nie-ine/inseri#421]
@rfbaumgartner which apps should we keep that you coded and which should we take out of the appshore for now @rfbaumgartner ?

**Comment by rfbaumgartner** [comment]
These can be taken out:

- AVP-Edition (can be deleted)
- Resource Creation (can be deleted)
- Edit Resource (can be deleted)
- Joined Text View (should be rewritten to standard ontologies)
- Hierarchical navigation with dynamic loading (should be rewritten to standard ontologies)

Some apps might be dropped later and also some can be removed from the code.

**Comment by rfbaumgartner** [comment]
Some apps are deleted with PR #624 and commit 6b108374d75f3f3b0e1ab59bce0d30fdbfe706d2 while other apps have their specific GitHub issue.

Can we close this issue?
