### ISSUE TITLE
OpenFile input parameters for the myFiles App 

### ISSUE THREAD

**Issue by OmniaKahla** [nie-ine/inseri#441]
Assigning the fileUrlPath to the correct inseriApps input parameters.
Works with the simple Image App only, as it has only one input parameter.

**Comment by janCstoffregen** [comment]
is this still the case? then we should do it together on Tuesday

**Comment by janCstoffregen** [comment]
can we have a look at this one more time tomorrow?

**Comment by janCstoffregen** [comment]
works now!
