### ISSUE TITLE
Naming and renaming the files

### ISSUE THREAD

**Issue by DDDOlga** [nie-ine/inseri#448]
Is it possible to rename a file in Inseri? What are the regulation concerning the length of the name and various special signs? Jy_3_AF.1-503.jpg would still be ok? What are the "forbidden" signs?

**Comment by OmniaKahla** [comment]
Currently, you cannot rename a file.
I will add this feature and will check the regulations of the file naming convention, But it shouldn't be different that the normal naming convention. We can add our regulations, and this should be added as well in the documentation, For instance that the file name shouldn't exceed 25 character, shouldn't include special characters such as  ~ ! @ # $ % ^ & * ( ) ` ; < > ? , [ ] { } ' " and | 
and so on. 
Let me finish this and will reply again.
Thanks for pointing this out.

**Comment by OmniaKahla** [comment]
Hi @DDDOlga,
I have added this feature, renaming files. I found that there is no need to make it more complex and add a lot of regulations. I just added that the user cannot rename a file with a name that is already exists in his files' list.
If you have any comment, please add it.
Thanks

**Comment by OmniaKahla** [comment]
Done.
