### ISSUE TITLE
There is the bug we noticed giving 'error' but with result.

### ISSUE THREAD

**Issue by janCstoffregen** [nie-ine/inseri#453]
when creating a sparql query and getting rdf/xml back

**Comment by janCstoffregen** [comment]
@hanscools zur info

**Comment by janCstoffregen** [comment]
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX human: <http://www.e-editiones.ch/ontology/human#>
PREFIX calendar: <http://www.e-editiones.ch/ontology/calendar#>
PREFIX document: <http://www.e-editiones.ch/ontology/document#>
PREFIX text: <http://www.e-editiones.ch/ontology/text#>
PREFIX publish: <http://www.e-editiones.ch/ontology/publishing#>
PREFIX infocar: <http://www.e-editiones.ch/ontology/information-carrier#>
PREFIX delille: <http://www.e-editiones.ch/ontology/delille#>


# RETRIEVE PERSONS WITH THEIR PROPERTIES:

CONSTRUCT {
    ?person
        a human:Person;
        ?hasDay ?day;
        ?hasPeriod ?period;
        human:personHasRole ?personRole;
        delille:hasExternalResource ?e;
        ?p ?o.
    ?day
        ?hasDate ?gD;
        calendar:hasJulianDayNumber ?jDN;
        calendar:hasMessage ?m.
    ?period
        calendar:hasGregorianStartDate ?sD;
        calendar:hasGregorianEndDate ?eD;
        calendar:hasStartJulianDayNumber ?sJDN;
        calendar:hasEndJulianDayNumber ?eJDN.
    ?personRole a ?PersonRole.
    ?e
        a document:HypertextDocument;
        text:hasNameLiteral ?n;
        document:isOnWebpage ?w.
    ?w
        a publish:WebPublication;
        infocar:webpageHasURL ?u.
    }

WHERE {
    ?person
        a human:Person;
        human:personHasRole ?personRole;
        ?p ?o.
    ?personRole a ?PersonRole.
    OPTIONAL {
        ?person ?hasPeriod ?period.
        ?period
            calendar:hasGregorianStartDate ?sD;
            calendar:hasGregorianEndDate ?eD;
            calendar:hasStartJulianDayNumber ?sJDN;
            calendar:hasEndJulianDayNumber ?eJDN.
        }
    OPTIONAL {
        ?person ?hasDay ?day.
        ?day
            ?hasDate ?gD;
            calendar:hasJulianDayNumber ?jDN;
            calendar:hasMessage ?m.
        }
    OPTIONAL {
        ?person delille:hasExternalResource ?e.
        ?e 
            a document:HypertextDocument;
            document:isOnWebpage ?w.
        OPTIONAL {?e text:hasNameLiteral ?n}
        ?w
            a publish:WebPublication;
            infocar:webpageHasURL ?u.
        }
    }

**Comment by domsteinbach** [comment]
There is no issue with the Query itself. It is simply http post related. As far as I see the post is simply using a wrong or no Content Type or accept header (415, unsupported text/plain)

Please make sure using the proper content types and accept headers. The examples below should do the job, but bare in mind, that there is not yet an application in inseri which is able to consume/display turtle data or n3. The only response supported for now is sparql-results+json or JSON-LD.

**specify what you are sending via "Content-Type":**
- A SPARQL query is using Content-type: application/sparql-query
- A SPARQL Update is using Content-type: application/sparql-update
- turtle data: Content-Type:text/turtle

**specify what you like to receive back via "Accept" headers of your post:**
- sparql11-result json (https://www.w3.org/TR/sparql11-results-json/): "Accept: application/sparql-results+json"
- JSON-LD: "Accept: application/ld+json"
- turtle data: "Accept: text/turtle"
- n triples: "Accept: application/n-triples"
