### ISSUE TITLE
file structure in folder-query does not display a working link

### ISSUE THREAD

**Issue by janCstoffregen** [nie-ine/inseri#462]
--> the following paths should be a working link, thus starting with http://........
/backend/files/...

<img width="1216" alt="Screenshot 2020-05-31 at 15 59 46" src="https://user-images.githubusercontent.com/25609132/83354282-d9378c80-a357-11ea-8a5f-8c90fc6d813b.png">

**Comment by janCstoffregen** [comment]
I think this only happens when multiple files are uploaded

**Comment by OmniaKahla** [comment]
Issue has been solved.
