### ISSUE TITLE
inseri SPARQL query Body

### ISSUE THREAD

**Issue by hanscools** [nie-ine/inseri#466]
Hi Jan,
When I open consecutively my project "SPARQL", the folder "Delille-project", and a file e.g. "delille-citer" the black body window at the page bottom is shown, but empty.
After clicking "Header" and then "Body" the query appears.
Could the query appear directly at opening the file?
Regards,
Hans

**Comment by janCstoffregen** [comment]
fixed, will be visible after next update of test instance
