### ISSUE TITLE
comment function for inseri

### ISSUE THREAD

**Issue by janCstoffregen** [nie-ine/inseri#473]
- [ ] per url in inser a comment can be added, since the url includes the page in a book that the user browsed to, the comment will be linked to the page.
-- a user browses to page 100 and adds a comment
-- a user can see his all of his comments of this project in a list, and the link next to it
-- when clicking on the link, the user gets back to the inseri-page and the page in the book that he browsed to and commented on

this will take one day, not more @domsteinbach @Padlina and it's valuable for every edition project that published a manifest / query link. a user can then copy and paste this link and thus import the book / page and add own comments

this will enable the user to import any book, sheet, etc, from any NIE-INE edition website, browse through it and comment on it, I would like to do this soon. @GerhardLauer for your notice as well

Thanks and best regards,
Jan

**Comment by Padlina** [comment]
@janCstoffregen for sure a very nice feature, so yes, no problems from my part. Thank you!

**Comment by janCstoffregen** [comment]
done
