### ISSUE TITLE
Plaintext viewer doesn't show content anymore

### ISSUE THREAD

**Issue by cyrill-martin** [nie-ine/inseri#479]
On the below-listed pages I have the following problem: 
A working query is mapped correctly to a plaintext viewer but the viewer doesn't show any content anymore (this used to work before).

- http://test-nieos.nie-ine.ch/page?actionID=5e5f5801fd54d5001ea466e3&page=5e5f5804fd54d5001ea466e5
- http://test-nieos.nie-ine.ch/page?actionID=5e5f5801fd54d5001ea466e3&page=5e5f58aafd54d5001ea466e9
- http://test-nieos.nie-ine.ch/page?actionID=5e5f5801fd54d5001ea466e3&page=5e5f5a32fd54d5001ea466ee
- http://test-nieos.nie-ine.ch/page?actionID=5e5f5801fd54d5001ea466e3&page=5e5f5a9cfd54d5001ea466f1

**Comment by janCstoffregen** [comment]
fixed, please check

**Comment by cyrill-martin** [comment]
Works!
