### ISSUE TITLE
Text Editor App saves data but doesn't show it

### ISSUE THREAD

**Issue by cyrill-martin** [nie-ine/inseri#480]
1. I open a Text Editor (app). 
2. I write something.
3. The text is shown in the app. 
4. I click 'save text and update page'
5. The text is gone and the app shows 'undefined'

However, the text is correctly saved when checking the current data through the file options.

**Comment by cyrill-martin** [comment]
This seems to happen within a specific Delille set only (?): 
http://test-nieos.nie-ine.ch/page?actionID=5e5f5801fd54d5001ea466e3&page=5e5f5be7fd54d5001ea466f7

**Comment by janCstoffregen** [comment]
fixed
