### ISSUE TITLE
Delille last tasks

### ISSUE THREAD

**Issue by janCstoffregen** [nie-ine/inseri#506]
1) new pie chart from Cyrill
queries and and microservices are in delille_dataviz

2) new grouped bar chart from Cyrill
queries and and microservices are in delille_dataviz

--> deadline 15th of July for 1 & 2 (that the apps are usable with an own json)

an own app for 3) and 4) (bc it looks much nicer and this is our showcase project) (we don't need a microservice)

3) page with poem + app for single verse view (with inseriParam updating the single verse view)
--> when I reach this point, I ask Roberta and Hans one time, if they refined the queries, if not I do it myself

4) similar to 3) for persons (list of persons + app for single person view)

I think that I can construct the other pages with no problem, once these are working.

Finally,

6) add css to website

7) hierarchy in pages

goal: finish at the 15th of August (the whole project)

**Comment by cyrill-martin** [comment]
There are 11 json files to use as inputs for the Delille charts in https://c4science.ch/source/delille_file_system_layer/browse/master/NIE_delille_dataViz/code/. 
It's the files starting with "INPUT". They are based on the queries and the according results files in the same folder. 

These INPUT files have been created with the script createAllInputs.py. 

In case of use of the microservice, you could use the single scripts with MS in the name (e.g. 1_MS_pieChart.py). They have been tested together with the correct query result files in the microservice.

**Comment by janCstoffregen** [comment]
thank you!!!

**Comment by janCstoffregen** [comment]
@Padlina probably done with the dataviz on 15th in the evening, like defined as the deadline

**Comment by janCstoffregen** [comment]
@Padlina not done yet, but am working on it, can @cyrill-martin's python-project be started locally by Prof. HM to write the descriptions, if it is this urgent? Otherwise, I will have it until next Monday for sure, it's just a lot to do for me for walser as well and I'm on holiday...

**Comment by Padlina** [comment]
@janCstoffregen no, that would be too difficult for him (he would have to install binaries on his Mac, which isn't easy). I wrote him that we've some delay. For Monday it is fine.

**Comment by janCstoffregen** [comment]
great, thank you!!!

**Comment by Padlina** [comment]
I found the following bugs/needed enhancements:

- Pie chart V2 : the legend is not completely showed (the width of the <svg> inside <div id="chart"> isn't enough)
- there is one file per page and not per app, which makes it a little bit complicated to handle when the JSON is very long (e.g. 650 verses in different charts)
- when adding a new app, the order of the already existing apps changes
- Grouped bar chart: when scrolling on the right the y axis should remain visible (to see the values, e.g. Number of citations)

**Comment by Padlina** [comment]
Another issue:

- after having changed the height of the description of e.g. a pie chart, and saved the page, the description height returns to the original

**Comment by janCstoffregen** [comment]
- Pie chart V2 : the legend is not completely shown (the width of the tag svg inside div id="chart" isn't enough) --> done

**Comment by janCstoffregen** [comment]
- there is one file per page and not per app, which makes it a little bit complicated to handle when the JSON is very long (e.g. 650 verses in different charts) --> https://github.com/nie-ine/inseri/issues/509 will do it later

**Comment by janCstoffregen** [comment]
- after having changed the height of the description of e.g. a pie chart, and saved the page, the description height returns to the original @Padlina --> how do you change the height of the description? by dragging? I have to disable dragging, bc this information is not saved for the description

**Comment by janCstoffregen** [comment]
- when adding a new app, the order of the already existing apps changes  https://github.com/nie-ine/inseri/issues/510

**Comment by janCstoffregen** [comment]
- it would be nice to be able to select the title and the text in a app description --> @Padlina you mean the cursor should be the "select" cursor?

**Comment by janCstoffregen** [comment]
- bar chart should be scalable as before (but actually re-rendering the chart, and not adding a new one below) @Padlina please specify more

**Comment by Padlina** [comment]
@Jan, some more details here: 

- yes, I change the height of the description  by dragging it
- select the title and the text in the app description: I mean that when you go over the title/text with the mouse and click on it, you should be able to select it, e.g. to copy it
- bar chart scalable: for the bar chart and the old stacked bar chart there was an input field to scale the chart. This is very useful, but there was a bug: when clickin on "scale" button, instead of re-rendering the chart in a new scale, it would add a new chart in new scale under the already existing chart, not actually changing the latter

**Comment by Padlina** [comment]
I found another bug:
- if I open a text editor to modify a file already saved in inseri, the changes will not be saved in the file

**Comment by Padlina** [comment]
The html text of a file is not rendered the same in the "Text Editor" and in the "Plainext Viewer"

**Comment by janCstoffregen** [comment]
> * yes, I change the height of the description  by dragging it
--> this means that the height automatically adjusts to the text.

> * select the title and the text in the app description: I mean that when you go over the title/text with the mouse and click on it, you should be able to select it, e.g. to copy it
--> ok, I will do it

> * bar chart scalable: for the bar chart and the old stacked bar chart there was an input field to scale the chart. This is very useful, but there was a bug: when clickin on "scale" button, instead of re-rendering the chart in a new scale, it would add a new chart in new scale under the already existing chart, not actually changing the latter
--> like at the other page

**Comment by Padlina** [comment]
Sankey diagram not working with default data.

**Comment by Padlina** [comment]
Strange bug: in the project "Delille Data Visualisations", I created a page "Bar Charts", but now I can't access it anymore. It is there, but when cliking on it it will redirect to the Dashboard.

**Comment by janCstoffregen** [comment]
regarding the links that do not work, this is because an app is surrounded by mat-card. I did not find the css class that disables the link, and I want to rewrite the app-structure anyway, withtout mat-card, so I will do it here: Improve location of settings-button of app for tiles #491

**Comment by janCstoffregen** [comment]
so, remaining one is: sankey diagram, all other are delegated or assigned to another story.

**Comment by janCstoffregen** [comment]
bar chart scalable: for the bar chart and the old stacked bar chart there was an input field to scale the chart. This is very useful, but there was a bug: when clickin on "scale" button, instead of re-rendering the chart in a new scale, it would add a new chart in new scale under the already existing chart, not actually changing the latter
--> like at the other page --> @cyrill-martin would you mind doing this? I am not good enough with d3 and draw all charts severyl times in the same div

**Comment by Padlina** [comment]
@Jan : 
new bug CSS-dependent (probably): in the grouped bar chart (v2) when clicking (to select/unselect them) on items on the legend the color of the box isn't set anymore on white (unselected) with colored border; then you don't know what you have selected and what not. This was working before.

**Comment by cyrill-martin** [comment]
> @jan :
> new bug CSS-dependent (probably): in the grouped bar chart (v2) when clicking (to select/unselect them) on items on the legend the color of the box isn't set anymore on white (unselected) with colored border; then you don't know what you have selected and what not. This was working before.

--> fixed with commit 4bd3d39

**Comment by janCstoffregen** [comment]
done
