### ISSUE TITLE
Grouped bar chart: when scrolling 

### ISSUE THREAD

**Issue by janCstoffregen** [nie-ine/inseri#511]
Grouped bar chart: when scrolling on the right the y axis should remain visible (to see the values, e.g. Number of citations)

**Comment by janCstoffregen** [comment]
@cyrill-martin please implement it in the original repo, where you created the chart, thank you!!!
@Padlina zur info

**Comment by cyrill-martin** [comment]
I now changed the layout approach to the grouped bar chart. If that works in inseri, it might be sensful to apply it to the regular bar chart as well. 

The chart is now divided up into two divs next to each other inside a container (\#chart_container):
- One div for the y-axis (\#yaxis)
- One div for the x-axis and the bars (\#chart)

```
<div id="chart_container">
    <div id="yaxis">
    </div>
    <div id="chart">
    </div>
</div>
```

With: 
```
#chart_container {
	position: relative;
}
#yaxis {
	position: absolute;
	float: left;
	z-index: 3;
}
#chart {
	position: relative;
	overflow-x: auto;
}
```

- It's mainly a layout (html/css) change. 
- In the d3.js code I took care that the SVGs get drawn into the correct divs. 
- However, @janCstoffregen: in the d3.js code I currently hard-coded the width of the legend, y-axis, and chart. inseri seems to have better/smarter handling of the chart width as it just gets wider if there are more bars. How does this work?

The files are changed accordingly in https://c4science.ch/source/delille_file_system_layer/browse/master/NIE_delille_dataViz/visualizations/

**Comment by janCstoffregen** [comment]
hi, thanks, let's discuss it today when to proceed together!

**Comment by cyrill-martin** [comment]
done with next inseri update on test server
