### ISSUE TITLE
add a text file and edit it with the textListViewer

### ISSUE THREAD

**Issue by janCstoffregen** [nie-ine/inseri#532]
this might currently be not possible, I have to chekc it, bc the textListViewer probably writes in his own json file, I have to take the default input out and make it overwrite the input file

**Comment by janCstoffregen** [comment]
should work again, you just need to map the text editor to the right part of the myOwnJson or the plainTextViewer myOwnJson to the textEditor

**Comment by janCstoffregen** [comment]
fixed, @Padlina @cyrill-martin @DDDOlga please try to edit sth with this if you have time, and come back to me if it does not work, thank you!

**Comment by cyrill-martin** [comment]
@janCstoffregen Works for me!

**Comment by janCstoffregen** [comment]
ok, great, thanks!
