### ISSUE TITLE
Cannot have 2 or more text viewers on the same page

### ISSUE THREAD

**Issue by DDDOlga** [nie-ine/inseri#544]
I would like to have 2 text viewers windows on the same page, but when I try to attach them to a different "text files" from two different "text editors" via Data management, only 1 is displayed.

**Comment by janCstoffregen** [comment]
hi, it works for me, do you use plaintext viewers and text editors?

**Comment by janCstoffregen** [comment]
hi, would you mind letting me know how I can reproduce this? @DDDOlga
