### ISSUE TITLE
Mapping json response for python microservice: inseri keeps saving and refreshing page in an endless loop

### ISSUE THREAD

**Issue by cyrill-martin** [nie-ine/inseri#545]
After launching the jsonEnvironment with a python file I do: 
1. Data Management
2. Duplicate exsting query
3. Choose a Delille sparql query (1_delille-citations-per-verse-per-citer-type_count.rq)
4. assignedJson > map
5. Choose whole json response
6. Save everything

After that the query seems to execute and it shows up in the Input area but the page keeps refreshing all the time so the input disappears and the query gets executed again...and again...and again.

**Comment by janCstoffregen** [comment]
solved, will update the testinstance now

**Comment by cyrill-martin** [comment]
The loop is still in place when the assigned json is mapped to the whole response. 
![Screenshot_2020-09-24 inseri](https://user-images.githubusercontent.com/25374540/94406935-0c0d5800-0173-11eb-9ab3-57e4d2468144.png)

**Comment by janCstoffregen** [comment]
fixed and published on test instance, please check if it works

**Comment by cyrill-martin** [comment]
Works. No more loop.
