### ISSUE TITLE
clickable links in templates

### ISSUE THREAD

**Issue by DDDOlga** [nie-ine/inseri#551]
Dear All,

It would be great to have a clickable links in the descriptions of the templates for IIIF resources.
<img width="989" alt="Screenshot 2020-09-08 at 10 49 36" src="https://user-images.githubusercontent.com/28563965/92454748-24680380-f1c1-11ea-9907-a35b840ba83c.png">

**Comment by domsteinbach** [comment]
Sorry, I was a little bit fast, Done with (https://github.com/nie-ine/inseri/commit/ed3f2495b170442562b8895a419a84523f8de9ab) . Please pull and check.

**Comment by domsteinbach** [comment]
It is done only in the textlist view and still has to be implemented in the description of the templates. It could be done in a similar fashion or via a Pipe (via Pipe it would be neat, as it could be imported and reused elsewhere).

**Comment by domsteinbach** [comment]
Now added an inseri wide link pipe in this [commit](https://github.com/nie-ine/inseri/commit/6a1ca633de20af19d93fb06b4a3913c88b75b48b)

The only thing left is to use it in the templates like done so in the dashboard.component.html 
`<p class="text-muted"  [innerHTML]= "action.description | linkify"></p>`
