### ISSUE TITLE
How do I write a new app?

### ISSUE THREAD

**Issue by janCstoffregen** [nie-ine/inseri#554]
this issue helps users creating a new app

@cyrill-martin @hanscools @Padlina  as a documentation! The app-name will be called ```machine reasoning``` in this example

**Comment by janCstoffregen** [comment]
1. Change to app directory and generate new app

```cd src/app/app-engine/apps ```

```ng g c machine-reasoning```

**Comment by janCstoffregen** [comment]
2. Add the new app to the open-apps model. This data model serves a page to describe which apps are open. The following example contains an entry in this model with all examples:

```typescript
    urlParamUpdater: {                    \\ <-- key of this app
      type: 'urlParamUpdater',         \\ <-- type of this app, needs to be the same name as the key
      model: [],
      inputs: [                                 \\ <-- this app has 2 inputs
        {
          'inputName': 'param',
          default: 'defaultParam'      \\ <-- this is the default input that is generated when a new app is opened
        },
        {
          'inputName': 'textFile',
          default: 'Please paste variable here and click save afterwards'
        }
      ],
      materialIcon: 'menu',       \\ this is a material icon, which is displayed in the app menu
      initialWidth: '375',           \\ initial width and height of the app
      initialHeight: '100',
      fullWidth: true,                \\ fullWidth and fullHeight can be true
    }
```

in our case, we don't have any inputs, our app looks the following way:

```typescript
    machineReasoning: {
      type: 'machineReasoning',
      model: [],
      materialIcon: 'blur_on',
      initialWidth: '600',
      initialHeight: '400'
    }
```

**Comment by janCstoffregen** [comment]
@hanscools which icon would you like for this app? https://material.io/resources/icons/?style=baseline

**Comment by janCstoffregen** [comment]
3. Add app to appMenuModel.ts This model serves for the pageMenu where a user can open new apps. It is a little redundant to the openAppModel, which can be improved in the future.

```typescript
    {
      id: 'blur_on',                                        <-- material icon, this is redundant and can be improved
      name: 'Machine Reasoning',             <-- Name in the page menu
      tags: 'N3, rdfs, rdf, owl',                    <-- nowhere displayed at the moment
      color: 'yellow',                                    <-- nowhere displayed at the moment
      status: 'under development',           <-- nowhere displayed at the moment
      appType: 'machineReasoning',        <-- must be the same as in openAppModel
      description: 'Reason with reason',  <-- nowhere displayed at the moment
      showOnHome: false,                        <-- show it when you are logged out or now
      appGroup: 'microservice'                 <-- which app group does it belong to?
    },
```

**Comment by hanscools** [comment]
> @hanscools which icon would you like for this app? https://material.io/resources/icons/?style=baseline
@janCstoffregen no really fitting icon found in this list; this one looks good and free download:
https://www.nicepng.com/ourpic/u2w7r5e6t4e6i1w7_about-us-ai-brain-icon-png/

**Comment by janCstoffregen** [comment]
@hanscools it needs to be one of the material icon list for now...

**Comment by janCstoffregen** [comment]
4. Step: Add the app to the all-app-selectors.component. Here a first example with all aspects:

```html
<data-list-view style="position: sticky;" *ngIf="app.type === 'dataListView'" <!-- needs to be the name defined in the previous models -->
                [queryResponse]="app.json" <!--  here you map the app inputs, that you have defined before -->
                [dataListSettings]="app.settings"  <!-- another input for this app -->
                [hash] = "app.hash" <!-- if the app saves sth in inseri, you need this -->
                [appInputQueryMapping] = "appInputQueryMapping" <!-- if the app saves sth in inseri, you need this -->
                [showSettings]="app.showSettings" <!-- another input for this app -->
                (reloadVariables)="reloadVariablesFunction()"> <!-- if the app saves sth in inseri, you need this -->
</data-list-view>
```

for our example it looks like this:

```html
<app-machine-reasoning *ngIf="app.type === 'machineReasoning'">

</app-machine-reasoning>
```

**Comment by janCstoffregen** [comment]
now you can open the app in the page menu
<img width="411" alt="Screenshot 2020-09-17 at 10 38 26" src="https://user-images.githubusercontent.com/25609132/93446853-fe81e380-f8d1-11ea-92e2-a467f67fc747.png">

**Comment by janCstoffregen** [comment]
and when you open it you see an empty app
<img width="1405" alt="Screenshot 2020-09-17 at 10 38 37" src="https://user-images.githubusercontent.com/25609132/93446892-093c7880-f8d2-11ea-8d98-1dd5079feaff.png">

**Comment by cyrill-martin** [comment]
I re-wrote this issue as a tutorial in the inseri documentation. 
inseri/Tutorials/Web component development/Create a new app/

**Comment by janCstoffregen** [comment]
great, thanks!!!
