### ISSUE TITLE
json environment: syntax highlighting

### ISSUE THREAD

**Issue by cyrill-martin** [nie-ine/inseri#564]
To set the correct syntax highlighting for the ace editor in angular you have to import the according module: 

E.g.

`import 'ace-builds/src-noconflict/mode-python';` 

Then you can do something like this:

HTML:
`<ace-editor #editor>`

TS:
```
@ViewChild('editor') editor;
this.editor.setMode('python') 
```

Or directly in the HTML: 
`<ace-editor [mode]="'python'">`

**Comment by janCstoffregen** [comment]
amazing!

**Comment by janCstoffregen** [comment]
done
