### ISSUE TITLE
Maximize the window of machine reasoning result

### ISSUE THREAD

**Issue by janCstoffregen** [nie-ine/inseri#565]
@hanscools fyi

**Comment by cyrill-martin** [comment]
If this is just for this app and not an inseri-wide thing, you could assign this to me. I wanted to take care of this anyway.

**Comment by cyrill-martin** [comment]
You can now set the results "full browser screen". However, the actual content of the ace editor somehow only resizes if you quickly change the size of the browser window...that's a bit annoying.

**Comment by cyrill-martin** [comment]
I close this for now...
