### ISSUE TITLE
html viewer documentation

### ISSUE THREAD

**Issue by janCstoffregen** [nie-ine/inseri#572]
- [x] The app is described for a researcher here: https://github.com/nie-ine/inseri/tree/2020-10/Tutorials/App%20descriptions%20for%20Researchers
- [x] There is a link in the README to the external repository if applicable (for instance to https://www.primefaces.org/primeng/showcase/#/editor for the text editor)
- [x] The functions and the variables in the code is either self explaining or have a comment above them
- [x] The link to the description is included here: https://github.com/nie-ine/inseri/blob/2020-10/src/app/user-action-engine/mongodb/page/open-apps.model.ts#L172 (we need this so that the user gets to the description directly from the app)
- [ ] It has been reviewed by @janCstoffregen

@GerhardLauer  fyi

**Comment by rfbaumgartner** [comment]
Both this app and the joined text view (mentioned in #591) share a component from `shared/rich-text/` in their core. Would it make sense to combine them into one module? Or what is the recommended procedure with apps and modules? @janCstoffregen

**Comment by janCstoffregen** [comment]
Hi @rfbaumgartner thank you for this question. In general, apps should be designed encapsulated. If one app breaks, the other one should still work. If this is given, you are free to design it as you think it makes sense.

**Comment by rfbaumgartner** [comment]
Then, the way will be a bit of code duplication which is justified in this case:

- Encapsulation reduces errors from moving or removing code
- Changes in the shared component could lead to consequences for every app including it. Common behaviour could be lost through repeated development but unexpected breaks are easier to detect.

**Comment by janCstoffregen** [comment]
yes, that sounds reasonable!
