### ISSUE TITLE
Radial Bar Chart doku

### ISSUE THREAD

**Issue by janCstoffregen** [nie-ine/inseri#587]
- [x] The app is described for a researcher here: https://github.com/nie-ine/inseri/tree/2020-10/Tutorials/App%20descriptions%20for%20Researchers
- [x] There is a link in the README to the external repository if applicable (for instance to https://www.primefaces.org/primeng/showcase/#/editor for the text editor)
- [x] The functions and the variables in the code is either self explaining or have a comment above them
- [x] The link to the description is included here: https://github.com/nie-ine/inseri/blob/2020-10/src/app/user-action-engine/mongodb/page/open-apps.model.ts#L172 (we need this so that the user gets to the description directly from the app)
- [ ] It has been reviewed by @janCstoffregen 

@GerhardLauer  fyi

**Comment by cyrill-martin** [comment]
@janCstoffregen I did some changes to the radial bar chart:

- All bars are shown completely (they don't shoot out of the chart anymore)
- There's a tooltip showing the value of each bar

I can do the documentation for the app if you want.
