### ISSUE TITLE
Joined text view

### ISSUE THREAD

**Issue by janCstoffregen** [nie-ine/inseri#591]
please review if it should be taken out, otherwise 

- [ ] The app is described for a researcher here: https://github.com/nie-ine/inseri/tree/2020-10/Tutorials/App%20descriptions%20for%20Researchers
- [x] There is a link in the README to the external repository if applicable (for instance to https://www.primefaces.org/primeng/showcase/#/editor for the text editor)
- [x] The functions and the variables in the code is either self explaining or have a comment above them
- [x] The link to the description is included here: https://github.com/nie-ine/inseri/blob/2020-10/src/app/user-action-engine/mongodb/page/open-apps.model.ts#L172 (we need this so that the user gets to the description directly from the app)
- [ ] It has been reviewed by @janCstoffregen

**Comment by rfbaumgartner** [comment]
After re-thinking about it, I am going to take this app out and move it to its own repository: https://github.com/rfbaumgartner/joined-text-view

Reasons

- The app is depending on Knora but follows a model not recommended for Knora projects with full Knora resources for text elements. Words and lines should be encoded with Knora standoff and queried a different way.
- Newer development for displaying standoff have not yet been considered. Querying standoff separately allows event handling in the frontend without repeated queries for resources.

Future

- This app will get its repo where it can be re-written to SPARQL with `select` covering the majority of triple stores.

**Comment by janCstoffregen** [comment]
ok, cool, thanks!!!
