### ISSUE TITLE
Anton Webern combined with GND

### ISSUE THREAD

**Issue by janCstoffregen** [nie-ine/inseri#602]
- [ ] The app is described for a researcher here: https://github.com/nie-ine/inseri/tree/2020-10/Tutorials/App%20descriptions%20for%20Researchers
- [ ] There is a link in the README to the external repository if applicable (for instance to https://www.primefaces.org/primeng/showcase/#/editor for the text editor)
- [ ] The functions and the variables in the code is either self explaining or have a comment above them
- [ ] The link to the description is included here: https://github.com/nie-ine/inseri/blob/2020-10/src/app/user-action-engine/mongodb/page/open-apps.model.ts#L172 (we need this so that the user gets to the description directly from the app)
- [ ] It has been reviewed by @musicEnfanthen 

@GerhardLauer  fyi

**Comment by musicEnfanthen** [comment]
@janCstoffregen Do you need me to do something?

Could you please check if GND epxosition is working as expected, since I recently changed the implementation on our side : https://github.com/webern-unibas-ch/awg-app/commit/69120b674d4718dc439b6a7923c8a0df11182e7d

**Comment by janCstoffregen** [comment]
@musicEnfanthen thanks for asking! After I document the GNU-App as described , let's have a look together if it still works!
