### ISSUE TITLE
delille - create all pages that should exist in the end

### ISSUE THREAD

**Issue by janCstoffregen** [nie-ine/inseri#620]
later move so that the page becomes a subpage

**Comment by Padlina** [comment]
I created all the needed pages under the inseri projects "L'Homme des champs : éditer une réception littéraire" and "Delille Data Visualisations".
Depending on the performance, we'll have to split datavisualisation on a page each (like it is now in "Delille Data Visualisations (microservice).

**Comment by janCstoffregen** [comment]
ok, but then I can close this for now
