### ISSUE TITLE
delille - list with poems and link to another page or app

### ISSUE THREAD

**Issue by janCstoffregen** [nie-ine/inseri#622]

**Comment by cyrill-martin** [comment]
For each verse, add relative link with URL parameter (sth. like ?verselabel=...)

**Comment by cyrill-martin** [comment]
I tested the microservice code for the poem HTML locally (without the SPARQL query). It works. 
But I'm not sure how the added URL parameter would ever work.
If I just add `<a href="?verselabel=verse-001">` in the Python code, it will default to http://test-nieos.nie-ine.ch/?verselabel=verse-001, overriding all other parameters. 
If I include some JavaScript in the HTML output of the microservice, I'm sure Angular will not accept it.

**Comment by janCstoffregen** [comment]
we'll just do it with the absolute links, please reopen issue if the page is reloading, when you click on the link, which should not be the case

**Comment by cyrill-martin** [comment]
I tested it with a static json input for the microservice on my account. 
The verse links are the same as the complete page url + &verselabel=verse-001, etc. 
The page reloads with every click.

**Comment by cyrill-martin** [comment]
@janCstoffregen http://test-nieos.nie-ine.ch/page?actionID=5f05a2763347be00298ffbc0&page=5f96f0f4a65e56001e21a3ee&5f96f125a65e56001e21a3ef=0

**Comment by cyrill-martin** [comment]
@janCstoffregen Here's the query to be triggered when clicking on a verse link. It's an example for verse number 1. So there should be a placeholder for the verse label at the beginning of the WHERE clause (thanks @Padlina). 

```
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix language: <http://e-editiones.ch/ontology/language#>
prefix text: <http://e-editiones.ch/ontology/text#>
prefix text-expression: <http://e-editiones.ch/ontology/text-expression#>
prefix prosodic-structure: <http://e-editiones.ch/ontology/prosodic-structure#>
prefix delille: <http://e-editiones.ch/ontology/delille#>


# RETRIEVE VERSES AND CITING EXPRESSIONS:

CONSTRUCT {
	?rhymingVerse
		a prosodic-structure:RhymingVerse;
		prosodic-structure:verseHasOrdinalNumeral ?verseOrdinalNumeral;
		language:hasContentLiteral ?rhymingVerseContentLiteral;
		text:isCitedIn ?citingExpression.
	?CitingExpression rdfs:subClassOf delille:CitingExpression.
	?citingExpression
		a ?CitingExpression;
		text-expression:hasTitleLiteral ?textExpressionTitleLiteral;
		delille:hasPunctuatedCitedVerseNumberSequenceLiteral ?punctuatedCitedVerseNumberSequenceLiteral.
	}

WHERE {
	?rhymingVerse
		rdfs:label "verse-001";
    	a prosodic-structure:RhymingVerse;
		prosodic-structure:verseHasOrdinalNumeral ?verseOrdinalNumeral;
		language:hasContentLiteral ?rhymingVerseContentLiteral;
		text:isCitedIn ?citingExpression.
	?CitingExpression rdfs:subClassOf delille:CitingExpression.
	?citingExpression
		a ?CitingExpression;
		text-expression:hasTitleLiteral ?textExpressionTitleLiteral;
		delille:hasPunctuatedCitedVerseNumberSequenceLiteral ?punctuatedCitedVerseNumberSequenceLiteral.
	}
```

**Comment by janCstoffregen** [comment]
Dear @cyrill-martin,
I added and pushed the following code to the textlist-Viewer. It listens to a click event in this component and checks if it's a link that has been clicked. It prevents the page from reloading (currently for all links) and appends a demoParameter without reloading.

Those are all the ingredients needed to proceed I think. Just adjust the link you emit in a generic way, and then a check in the textlist-component, that checks if you are on the same action (if the page changes, not the whole inseri is reloaded either) If you are on the same action, just append the diff between the emitted link and this.router.url.

Looking forward how it goes, let me know if I did not consider sth.

Thank you so much and best regards,
Jan

```typescript
  @HostListener('click', ['$event'])
  public onClick(event) {
    console.log(event.target.href);
    console.log( this.router.url );
    const demoParams = {
      testParam: 'test'
    }
    if (event.target.tagName === 'A') {
      this.router.navigate( ['/page'], {
        queryParams: demoParams,
        queryParamsHandling: 'merge'
      } );
      event.preventDefault();
    } else {
      return;
    }
  }
```

**Comment by cyrill-martin** [comment]
I pushed a solution with commit f91e220 but it's now in conflict with the bookmark links for the endnotes. I have to solve this Monday.

**Comment by cyrill-martin** [comment]
I will introduce a different solution than the already pushed one, just had an enlightment.

**Comment by cyrill-martin** [comment]
- Verse labels are added to the current URL without reloading the page (e.g. &verselabel=verse-001)
- Page scrolls to endnotes and back to endnote reference in the poem without reloading the page 

Works in a generic way for microservice-generated HTML.

**Comment by cyrill-martin** [comment]
I re-open as I'm not yet sure how to link the verse link to another app which then queries the triple store.

**Comment by janCstoffregen** [comment]
hi, we can do that together tomorrow?

**Comment by janCstoffregen** [comment]
it still reloads for me, but the url is updated, let's figure it out together tomorrow

**Comment by cyrill-martin** [comment]
ok, lets see tomorrow
