### ISSUE TITLE
delille - text editor doesn't work

### ISSUE THREAD

**Issue by Padlina** [nie-ine/inseri#629]
I wanted to change the html file here http://test-nieos.nie-ine.ch/page?actionID=5f156c8d8f60aa002955b185&page=5f156c8e8f60aa002955b187&5f48ce31ad61a1002935aac2=NaN&5f15d9508f60aa002955b19d=0
but when clicking on "Save text and Update page" in the text editor, there is an error:
"ERROR TypeError: this.appInputQueryMapping[hashOfOriginalFileOwnerApp] is undefined"

**Comment by janCstoffregen** [comment]
both apps were linked to an app that has been closed. i opened 2 new apps, linked them and it works

**Comment by Padlina** [comment]
I have the same problem on another page (http://test-nieos.nie-ine.ch/page?actionID=5f156c8d8f60aa002955b185&page=5f93e34c3eff2f001e0a490f&5f93ed143eff2f001e0a4912=NaN&5f93e5ba3eff2f001e0a4910=0). I tried to close both apps and reopen, re-assign to query (exact same path), but I still get the error: ERROR TypeError: this.appInputQueryMapping[hashOfOriginalFileOwnerApp] is undefined[](url)

**Comment by janCstoffregen** [comment]
Both apps were again linked the the content of an app that is not open anymore. I have to agree that this kind of bug needs to be solved. For now, close both apps, open a text editor, open a plaintext viewer and link the input of the plaintext viewer to the textfile of the text editor, then updating works. sorry for the incovenience
