### ISSUE TITLE
delille - stacked bar chart v2

### ISSUE THREAD

**Issue by Padlina** [nie-ine/inseri#632]
@cyrill-martin Would be possible to enhance the stacked bar chart as was done for the (grouped) bar chart V2 ? I don't know how much time this would require, but it would be great!

**Comment by cyrill-martin** [comment]
The stacked bar chart (pushed to branch 2020-10) now looks like the other bar charts. Same colors, same legend/chart layout. Similar tooltip. You can sort by value, manually scale it and select groups/stacks to be shown or not. But there's no fancy transition between toggling the stacks, they just appear or disappear. 
![Peek 2020-10-28 14-17](https://user-images.githubusercontent.com/25374540/97440950-6e9b7480-1928-11eb-866c-9dbb4deaa6a3.gif)

**Comment by Padlina** [comment]
@cyrill-martin Perfect, it's really cool! Thank you very much!

**Comment by cyrill-martin** [comment]
@janCstoffregen We need to change the default input data for the stacked bar chart. 
The key for the stack labels should be just "label" instead of "xValue".

**Comment by cyrill-martin** [comment]
Issue with two stacked bar charts on the same page

**Comment by cyrill-martin** [comment]
> @janCstoffregen We need to change the default input data for the stacked bar chart.
> The key for the stack labels should be just "label" instead of "xValue".
> Not sure where/how I do this.

Done, found it
