### ISSUE TITLE
delille - improve radial bar chart

### ISSUE THREAD

**Issue by Padlina** [nie-ine/inseri#633]
- fix dimensions, so that the whole graphic is visibile
- the sections should follow the numberal order of the strophes (1,2,3 ... instead of 1,10,11,12...)

**Comment by janCstoffregen** [comment]
@Padlina will you pojnt me to the page with the right data

**Comment by Padlina** [comment]
@janCstoffregen here: http://test-nieos.nie-ine.ch/page?actionID=5f156c8d8f60aa002955b185&page=5f169a728f60aa002955b19f&5f156d5f8f60aa002955b18c=NaN&5f169a798f60aa002955b1a0=0

**Comment by janCstoffregen** [comment]
ok, I started, it's better now, but @cyrill-martin would you mind having a look at radial-barchart.component.ts line 95

is there is d3js-way to sort it? Otherwise I have to write a function manually...

**Comment by janCstoffregen** [comment]
it's not on the test instance yet

**Comment by cyrill-martin** [comment]
> ok, I started, it's better now, but @cyrill-martin would you mind having a look at radial-barchart.component.ts line 95
> 
> is there is d3js-way to sort it? Otherwise I have to write a function manually...

I can look at it tomorrow

**Comment by cyrill-martin** [comment]
@janCstoffregen D3 iterates over the input data in the order it is received. 
So the very easiest would be to just provide the input in the correct order which is done somewhere else. 
The input data's labels are now "1", "10", "11", etc. and therefore shown in this order. I think that makes sense at it could also be some nominal order in other cases.

**Comment by janCstoffregen** [comment]
@cyrill-martin thank you for this information. @Padlina in other words, you just need to change your input the way you want it to be, the app does not do any kind of sorting, it must have happened in your code before you put it in the app
