### ISSUE TITLE
Grouped bar chart bug

### ISSUE THREAD

**Issue by Padlina** [nie-ine/inseri#639]
If you select 1500 as chart width, and then deselect one of the category, all the bars disappears and then the whole selection of categories doesn't work as expected.
This seems to happen only when the bars are very small.
![grouped-bar-chart1](https://user-images.githubusercontent.com/30690002/97672237-f64cc480-1a89-11eb-9758-597f74a92f73.png)
![grouped-bar-chart2](https://user-images.githubusercontent.com/30690002/97672240-f77df180-1a89-11eb-8002-30a31e28758e.png)

**Comment by cyrill-martin** [comment]
Fixed with commit 2bc53b2 to branch 2020-10.
I omitted the re-calculation of the total width of each x-axis item (each verse in this case) when deselecting one of the groups. 
When the single bars were very small, this always led to a new total width of zero and all bars were gone.
