### ISSUE TITLE
minimize apps

### ISSUE THREAD

**Issue by janCstoffregen** [nie-ine/inseri#672]
... and only show it in the navigatoin bar, as discussed

@OmniaKahla let me know when you need this feauture

also password protect it, so that only users who know the password can change it

**Comment by OmniaKahla** [comment]
Dear @janCstoffregen ,
Thanks, I would really need in 2 weeks. 
After 2 weeks, I will need to integerate everything to inseri.swiss and other collaborators will use it as well. 
I really appreciate your help
Thank you.

**Comment by janCstoffregen** [comment]
ok, noted, so until the 12.04?

**Comment by OmniaKahla** [comment]
Ok, perfect. Thank you

**Comment by OmniaKahla** [comment]
Dear @janCstoffregen ,
I added the angular Material dialog, Please check and feedback. 
The logic is as follows:
- The user opens the dialog box, if the firstTime var is True
   - The user adds his credentials and it should be saved and the firstTime is false then
- If the firstTime is false
   - The user puts his credentials, if they are correct, he can change his credentials.


I am thinking to have them all in the same button, **no need for the lock button.** 
If the user minimize the app, the dialog appears to create his credentials. 
If the app is already minimized and the user click to open the minimzed app, the dialog should appear to ask him for the credentials. what do you think? 

Thanks and regards
Omnia

**Comment by OmniaKahla** [comment]
Dear @janCstoffregen,
I made the below changes, please let me know if these changes are better or to roll back to the previous one. 
- Now, the user minimize the app, the dialog appears to enter the user name and password, then the app is minimized. 
- The user open the minimized app, the dialog appears to enter the user name and password, if they are correct, the app opens else an alert msg pop up to tell him to enter the correct credentials. 

The only missing part is to add the user name and password in the db. Now, this is your part :) 

Please let me know if anything else is required from my side. I am currently working on #675 

Thanks and regards
Omnia

**Comment by janCstoffregen** [comment]
Hi, I'll take a look this evening, thank you for bringing this to this advanced poitn already, I'll do the last step until tomorrow at our meeting.

**Comment by janCstoffregen** [comment]
implemented
