### ISSUE TITLE
include text-structure components into page

### ISSUE THREAD

**Issue by rfbaumgartner** [nie-ine/inseri#91]
In der Page sollten folgende Komponenten als Apps auswählbar sein:

- [ ] TextPageOfWordsComponent (ComplexTextViewsModule)
- [ ] TextSvgViewComponent (ComplexTextViewsModule)
- [ ] TextLineComponent (TextStructureModule)
- [ ] TextLineGroupComponent (TextStructureModule)
- [ ] TextPageOfWordsComponent und TextSvgViewComponent haben gemeinsame Variablen (global) und wahlweise gleichen Inhalt (Textbaum)

Beispiele von Input etc. sind in `nieOS/src/app/development-views/text-dev-view/text-dev-view/text-dev-view.component.html`

**Comment by janCstoffregen** [comment]
I'll close this for now if it's ok
